# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ocr.proto',
  package='ocr',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tocr.proto\x12\x03ocr\"6\n\x14TextDetectionRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"+\n\x15TextDetectionResponse\x12\x12\n\njsonString\x18\x01 \x01(\t\"\"\n\x0cJSONResponse\x12\x12\n\njsonString\x18\x01 \x01(\t2H\n\x0cTextDetector\x12\x38\n\x06\x64\x65tect\x12\x19.ocr.TextDetectionRequest\x1a\x11.ocr.JSONResponse\"\x00\x62\x06proto3'
)




_TEXTDETECTIONREQUEST = _descriptor.Descriptor(
  name='TextDetectionRequest',
  full_name='ocr.TextDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='ocr.TextDetectionRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ocr.TextDetectionRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=72,
)


_TEXTDETECTIONRESPONSE = _descriptor.Descriptor(
  name='TextDetectionResponse',
  full_name='ocr.TextDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonString', full_name='ocr.TextDetectionResponse.jsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=117,
)


_JSONRESPONSE = _descriptor.Descriptor(
  name='JSONResponse',
  full_name='ocr.JSONResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonString', full_name='ocr.JSONResponse.jsonString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['TextDetectionRequest'] = _TEXTDETECTIONREQUEST
DESCRIPTOR.message_types_by_name['TextDetectionResponse'] = _TEXTDETECTIONRESPONSE
DESCRIPTOR.message_types_by_name['JSONResponse'] = _JSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextDetectionRequest = _reflection.GeneratedProtocolMessageType('TextDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTDETECTIONREQUEST,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:ocr.TextDetectionRequest)
  })
_sym_db.RegisterMessage(TextDetectionRequest)

TextDetectionResponse = _reflection.GeneratedProtocolMessageType('TextDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTDETECTIONRESPONSE,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:ocr.TextDetectionResponse)
  })
_sym_db.RegisterMessage(TextDetectionResponse)

JSONResponse = _reflection.GeneratedProtocolMessageType('JSONResponse', (_message.Message,), {
  'DESCRIPTOR' : _JSONRESPONSE,
  '__module__' : 'ocr_pb2'
  # @@protoc_insertion_point(class_scope:ocr.JSONResponse)
  })
_sym_db.RegisterMessage(JSONResponse)



_TEXTDETECTOR = _descriptor.ServiceDescriptor(
  name='TextDetector',
  full_name='ocr.TextDetector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=155,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='detect',
    full_name='ocr.TextDetector.detect',
    index=0,
    containing_service=None,
    input_type=_TEXTDETECTIONREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTDETECTOR)

DESCRIPTOR.services_by_name['TextDetector'] = _TEXTDETECTOR

# @@protoc_insertion_point(module_scope)
