# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ocr_pb2 as ocr__pb2


class TextDetectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.detect = channel.unary_unary(
        '/ocr.TextDetector/detect',
        request_serializer=ocr__pb2.TextDetectionRequest.SerializeToString,
        response_deserializer=ocr__pb2.JSONResponse.FromString,
        )


class TextDetectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def detect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextDetectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'detect': grpc.unary_unary_rpc_method_handler(
          servicer.detect,
          request_deserializer=ocr__pb2.TextDetectionRequest.FromString,
          response_serializer=ocr__pb2.JSONResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ocr.TextDetector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
