# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import search_pb2 as search__pb2


class SearchDocumentsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.simpleSearch = channel.unary_unary(
                '/search.SearchDocuments/simpleSearch',
                request_serializer=search__pb2.SearchDocumentsRequest.SerializeToString,
                response_deserializer=search__pb2.SearchDocumentsResponse.FromString,
                )


class SearchDocumentsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def simpleSearch(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchDocumentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'simpleSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.simpleSearch,
                    request_deserializer=search__pb2.SearchDocumentsRequest.FromString,
                    response_serializer=search__pb2.SearchDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.SearchDocuments', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchDocuments(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def simpleSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search.SearchDocuments/simpleSearch',
            search__pb2.SearchDocumentsRequest.SerializeToString,
            search__pb2.SearchDocumentsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
