# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='search.proto',
  package='search',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csearch.proto\x12\x06search\"o\n\x16SearchDocumentsRequest\x12\x13\n\x0bsearchTerms\x18\x01 \x03(\t\x12\r\n\x05index\x18\x02 \x01(\t\x12\x11\n\tfuzziness\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ields\x18\x04 \x03(\t\x12\x0e\n\x06userId\x18\x05 \x01(\t\"&\n\x17SearchDocumentsResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t2d\n\x0fSearchDocuments\x12Q\n\x0csimpleSearch\x12\x1e.search.SearchDocumentsRequest\x1a\x1f.search.SearchDocumentsResponse\"\x00\x62\x06proto3'
)




_SEARCHDOCUMENTSREQUEST = _descriptor.Descriptor(
  name='SearchDocumentsRequest',
  full_name='search.SearchDocumentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='searchTerms', full_name='search.SearchDocumentsRequest.searchTerms', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='search.SearchDocumentsRequest.index', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuzziness', full_name='search.SearchDocumentsRequest.fuzziness', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='search.SearchDocumentsRequest.fields', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='search.SearchDocumentsRequest.userId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=135,
)


_SEARCHDOCUMENTSRESPONSE = _descriptor.Descriptor(
  name='SearchDocumentsResponse',
  full_name='search.SearchDocumentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='search.SearchDocumentsResponse.ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['SearchDocumentsRequest'] = _SEARCHDOCUMENTSREQUEST
DESCRIPTOR.message_types_by_name['SearchDocumentsResponse'] = _SEARCHDOCUMENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchDocumentsRequest = _reflection.GeneratedProtocolMessageType('SearchDocumentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHDOCUMENTSREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:search.SearchDocumentsRequest)
  })
_sym_db.RegisterMessage(SearchDocumentsRequest)

SearchDocumentsResponse = _reflection.GeneratedProtocolMessageType('SearchDocumentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHDOCUMENTSRESPONSE,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:search.SearchDocumentsResponse)
  })
_sym_db.RegisterMessage(SearchDocumentsResponse)



_SEARCHDOCUMENTS = _descriptor.ServiceDescriptor(
  name='SearchDocuments',
  full_name='search.SearchDocuments',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=177,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='simpleSearch',
    full_name='search.SearchDocuments.simpleSearch',
    index=0,
    containing_service=None,
    input_type=_SEARCHDOCUMENTSREQUEST,
    output_type=_SEARCHDOCUMENTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEARCHDOCUMENTS)

DESCRIPTOR.services_by_name['SearchDocuments'] = _SEARCHDOCUMENTS

# @@protoc_insertion_point(module_scope)
